`ifndef rhAhb5TransBase__svh
`define rhAhb5TransBase__svh
/************************************************************************************/
// Author: RyanHunter
// Created: 2022-12-21 05:03:08 -0800
// Description:
// This file is automatically generated by MDC-v2, any issues found
// here should be modified in its source markdown document the same
// dir structure in Git/Obsidian/...
/************************************************************************************/

class RhAhb5TransBase extends uvm_sequence_item;
	realtime stime,etime; // record time for the trans start/end
	bit started = 0;
	`uvm_object_utils_begin(RhAhb5TransBase)
	`uvm_object_utils_end
	extern function void record(realtime t);
	extern function  new(string name="RhAhb5TransBase");
endclass
function void RhAhb5TransBase::record(realtime t);
	if (started) etime = t;
	else begin
		stime = t;
		started = 1;
	end
endfunction
function  RhAhb5TransBase::new(string name="RhAhb5TransBase");
	super.new(name);
endfunction

`endif
