`ifndef rhAhb5IfControlBase__svh
`define rhAhb5IfControlBase__svh
/************************************************************************************/
// Author: RyanHunter
// Created: 2022-12-20 09:11:55 -0500
// Description:
// This file is automatically generated by MDC-v2, any issues found
// here should be modified in its source markdown document the same
// dir structure in Git/Obsidian/...
/************************************************************************************/

class RhAhb5IfControlBase extends uvm_object;
	`uvm_object_utils_begin(RhAhb5IfControlBase)
	`uvm_object_utils_end
	extern virtual task driveAddressPhase(RhAhb5TransBeat b, bit waitReady);
	extern virtual task driveDataPhase(ref RhAhb5TransBeat b,output bit isError);
	extern virtual task waitDataPhase(ref RhAhb5TransBeat b,output bit isError);
	extern virtual task getResetChanged(output logic s);
	extern virtual task sync(int cycle);
	extern virtual function uvm_bitstream_t getSignal(string signame);
	extern function  new(string name="RhAhb5IfControlBase");
endclass
task RhAhb5IfControlBase::driveAddressPhase(RhAhb5TransBeat b, bit waitReady);
endtask
task RhAhb5IfControlBase::driveDataPhase(ref RhAhb5TransBeat b,output bit isError);
endtask
task RhAhb5IfControlBase::waitDataPhase(ref RhAhb5TransBeat b,output bit isError);
endtask
task RhAhb5IfControlBase::getResetChanged(output logic s);
endtask
task RhAhb5IfControlBase::sync(int cycle);
	// overridden by sub class
endtask
function uvm_bitstream_t RhAhb5IfControlBase::getSignal(string signame);
endfunction
function  RhAhb5IfControlBase::new(string name="RhAhb5IfControlBase");
	super.new(name);
endfunction

`endif
