`ifndef rhAhb5If__sv
`define rhAhb5If__sv
/************************************************************************************/
// Author: RyanHunter
// Created: 2022-12-20 09:11:54 -0500
// Description:
// This file is automatically generated by MDC-v2, any issues found
// here should be modified in its source markdown document the same
// dir structure in Git/Obsidian/...
/************************************************************************************/

interface RhAhb5If #( AW=32,DW=32)(input logic HCLK,input logic HRESETN);
	logic [AW-1:0] HADDR;
	logic [1:0] HTRANS;
	logic [2:0] HBURST;
	logic [3:0] HMASTER;
	logic [2:0] HSIZE;
	logic [7:0] HPROT;
	logic [DW-1:0] HWDATA;
	logic HMASTLOCK;
	logic HNONSEC;
	logic HEXCL;
	logic HWRITE;
	logic HLOCK;
	logic [1:0] HRESP;
	logic [DW-1:0] HRDATA;
	logic HREADY;
	logic HEXOKAY;
endinterface

`endif
