`ifndef omosEnv__svh
`define omosEnv__svh
// uvm_env: omosEnv
// This class generated by snippet: 'env', if has any issue, pls report to RyanHunter
`uvm_analysis_imp_decl(_mstReqImp)
`uvm_analysis_imp_decl(_mstReqDataImp)
`uvm_analysis_imp_decl(_mstRspImp)
`uvm_analysis_imp_decl(_slvReqImp)
`uvm_analysis_imp_decl(_slvReqDataImp)
`uvm_analysis_imp_decl(_slvRspImp)
class omosEnv extends uvm_env;
	RhAhb5Vip mst,slv;
	RhAhb5MstConfig mstc;
	RhAhb5SlvConfig slvc;
	RhuDebugger debug;

	uvm_analysis_imp_mstReqImp    #(RhAhb5ReqTrans,omosEnv) mreqI;
	uvm_analysis_imp_mstReqDataImp#(RhAhb5ReqTrans,omosEnv) mreqDataI;
	uvm_analysis_imp_mstRspImp    #(RhAhb5RspTrans,omosEnv) mrspI;
	uvm_analysis_imp_slvReqImp    #(RhAhb5ReqTrans,omosEnv) sreqI;
	uvm_analysis_imp_slvReqDataImp#(RhAhb5ReqTrans,omosEnv) sreqDataI;
	uvm_analysis_imp_slvRspImp    #(RhAhb5RspTrans,omosEnv) srspI;

	`uvm_component_utils_begin(omosEnv)
	`uvm_component_utils_end

	function new(string name="omosEnv",uvm_component parent=null);
		super.new(name,parent);
		debug = new(this,"component");
	endfunction
	// phases ##{{{
	extern virtual function void build_phase(uvm_phase phase);
	extern virtual function void connect_phase(uvm_phase phase);
	extern virtual task run_phase(uvm_phase phase);
	// ##}}}

	extern function void write_mstReqImp(RhAhb5ReqTrans _tr);
	extern function void write_mstReqDataImp(RhAhb5ReqTrans _tr);
	extern function void write_mstRspImp(RhAhb5RspTrans _tr);
	extern function void write_slvReqImp(RhAhb5ReqTrans _tr);
	extern function void write_slvReqDataImp(RhAhb5ReqTrans _tr);
	extern function void write_slvRspImp(RhAhb5RspTrans _tr);

endclass
function void omosEnv::write_mstReqImp(RhAhb5ReqTrans _tr);
	`uvm_info("GETTRANS",$sformatf("get master's reqCtrl tr:\n%s",_tr.sprint),UVM_LOW)
endfunction
function void omosEnv::write_mstReqDataImp(RhAhb5ReqTrans _tr);
	`uvm_info("GETTRANS",$sformatf("get master's reqData tr:\n%s",_tr.sprint),UVM_LOW)
endfunction
function void omosEnv::write_mstRspImp(RhAhb5RspTrans _tr);
	`uvm_info("GETTRANS",$sformatf("get master's rsp tr:\n%s",_tr.sprint),UVM_LOW)
endfunction

function void omosEnv::write_slvReqImp(RhAhb5ReqTrans _tr);
	`uvm_info("GETTRANS",$sformatf("get slave's reqCtrl tr:\n%s",_tr.sprint),UVM_LOW)
endfunction
function void omosEnv::write_slvReqDataImp(RhAhb5ReqTrans _tr);
	`uvm_info("GETTRANS",$sformatf("get slave's reqData tr:\n%s",_tr.sprint),UVM_LOW)
endfunction
function void omosEnv::write_slvRspImp(RhAhb5RspTrans _tr);
	`uvm_info("GETTRANS",$sformatf("get slave's rsp tr:\n%s",_tr.sprint),UVM_LOW)
endfunction

function void omosEnv::build_phase(uvm_phase phase); // ##{{{
	super.build_phase(phase);
	`debug("local build_phase starting ...")
	mst  = RhAhb5Vip::type_id::create("mst",this);
	$cast(mstc,mst.createConfig(RHAHB5_MASTER,"top.ifCtrl"));
	slv  = RhAhb5Vip::type_id::create("slv",this);
	$cast(slvc,slv.createConfig(RHAHB5_SLAVE,"top.ifCtrl"));

	// basic configs
	mstc.setActivePassive(UVM_ACTIVE);
	slvc.setActivePassive(UVM_ACTIVE);
	slvc.response(RHAHB5_RANDOM);

	// TODO, reqI=new("ahb.reqI",this);
	// TODO, reqDataI=new("ahb.reqDataI",this);
	// TODO, rspI=new("ahb.rspI",this);
	`debug($sformatf("build master with basic config:\n%s",mstc.sprint()))
	`debug($sformatf("build slave with basic config:\n%s",slvc.sprint()))

	mreqI     = new("mreqI",this);
	mreqDataI = new("mreqDataI",this);
	mrspI     = new("mrspI",this);
	sreqI     = new("sreqI",this);
	sreqDataI = new("sreqDataI",this);
	srspI     = new("srspI",this);
	`debug("local build_phase leaving ...")
	debug.updateChildren(this);
endfunction // ##}}}
function void omosEnv::connect_phase(uvm_phase phase); // ##{{{
	super.connect_phase(phase);
	`uvm_info("connect","running in connect_phase ...",UVM_LOW)
	mst.reqCtrlP.connect(mreqI);
	mst.reqDataP.connect(mreqDataI);
	mst.rspP.connect    (mrspI);
	slv.reqCtrlP.connect(sreqI);
	slv.reqDataP.connect(sreqDataI);
	slv.rspP.connect    (srspI);
endfunction // ##}}}
task omosEnv::run_phase(uvm_phase phase); // ##{{{
	super.run_phase(phase);
endtask // ##}}}

`endif
