`ifndef rhAhb5MstAgent__svh
`define rhAhb5MstAgent__svh
/************************************************************************************/
// Author: RyanHunter
// Created: 2022-12-22 06:29:21 -0800
// Description:
// This file is automatically generated by MDC-v2, any issues found
// here should be modified in its source markdown document the same
// dir structure in Git/Obsidian/...
/************************************************************************************/

class RhAhb5MstAgent#(type REQ=RhAhb5ReqTrans,RSP=RhAhb5RspTrans)
	extends uvm_agent;

	uvm_analysis_export #(REQ) reqCtrlP;
	uvm_analysis_export #(REQ) reqDataP;
	uvm_analysis_export #(RSP) rspP;
	RhAhb5MstDriver  drv;
	RhAhb5MstMonitor mon;
	RhAhb5MstSeqr    seqr;
	RhAhb5MstConfig  config;
	`uvm_component_utils_begin(RhAhb5MstAgent)
	`uvm_component_utils_end
	extern virtual function void build_phase(uvm_phase phase);
	// tobe deleted, extern function RhAhb5MstConfig createConfig(string name);
	// extern local function void __setupConfigureTable__();
	extern function void setupSubComponents();
	extern virtual function void connect_phase(uvm_phase phase);
	extern function  new(string name="RhAhb5MstAgent",uvm_component parent=null);
	extern virtual task run_phase(uvm_phase phase);
endclass
function void RhAhb5MstAgent::build_phase(uvm_phase phase);
	super.build_phase(phase);
	reqCtrlP = new("reqCtrlP",this);
	reqDataP = new("reqDataP",this);
	rspP = new("rspP",this);
	// __setupConfigureTable__();
	setupSubComponents();
endfunction
//tobe deleted, function RhAhb5MstConfig RhAhb5MstAgent::createConfig(string name);
//tobe deleted, 	config = RhAhb5MstConfig::type_id::create(name);
//tobe deleted, 	return config;
//tobe deleted, endfunction
//function void RhAhb5MstAgent::__setupConfigureTable__();
//	if (!uvm_config_db#(RhAhb5IfControlBase)::get(null,"*",config.interfacePath,config.ifCtrl))
//		`uvm_fatal("NIFC","no interface controller get")
//endfunction
function void RhAhb5MstAgent::setupSubComponents();
	if (is_active==UVM_ACTIVE) begin
		`rhudbg("this master agent is active building")
		drv = RhAhb5MstDriver::type_id::create("drv",this);
		drv.config = config;
		seqr= RhAhb5MstSeqr::type_id::create("seqr",this);
	end
	mon = RhAhb5MstMonitor::type_id::create("mon",this);
	mon.config = config;
endfunction
function void RhAhb5MstAgent::connect_phase(uvm_phase phase);
	super.connect_phase(phase);
	if (is_active==UVM_ACTIVE) begin
		`rhudbg("this master agent is active connecting")
		mon.resetP.connect(drv.resetI);
		drv.seq_item_port.connect(seqr.seq_item_export);
		drv.reqP.connect(mon.reqI);
	end
	mon.reqP.connect(reqCtrlP);
	mon.wreqP.connect(reqDataP);
	mon.rspP.connect(rspP);
endfunction
function  RhAhb5MstAgent::new(string name="RhAhb5MstAgent",uvm_component parent=null);
	super.new(name,parent);
endfunction
task RhAhb5MstAgent::run_phase(uvm_phase phase);
	super.run_phase(phase);
endtask

`endif
