
`ifndef rhAhb5IncrBurstSeq__svh
`define rhAhb5IncrBurstSeq__svh
/************************************************************************************/
// Author: RyanHunter
// Created: 2022-12-22 06:29:21 -0800
// Description:
// This file is automatically generated by MDC-v2, any issues found
// here should be modified in its source markdown document the same
// dir structure in Git/Obsidian/...
/************************************************************************************/

class RhAhb5IncrBurstSeq extends RhAhb5SeqBase;
	int len = 1;
	
	`uvm_object_utils_begin(RhAhb5IncrBurstSeq);
		`uvm_field_int(len,UVM_ALL_ON)
	`uvm_object_utils_end

	function new(string name = "RhAhb5IncrBurstSeq");
		super.new(name);
	endfunction

	extern task body ();
endclass

task RhAhb5IncrBurstSeq::body();
	rhahb5_htrans_enum _htrans = RHAHB5_NONSEQ;
	for (int i=0;i<len;i++) begin
		RhAhb5ReqTrans _req=new("req");
		if (i>0) _htrans=RHAHB5_SEQ;
		
		__addr += (2**__size);
		_req.randomize() with {
			trans == _htrans;
			burst == RHAHB5_INCR;
			size  == __size  ;
			prot  == __prot  ;
			addr  == __addr  ;
			lock  == __lock  ;
			nonsec== __nonsec;
			excl  == __excl  ;
			master== __master;
			write == __write ;
			wdata == __wdata ;
		// @RyanH	delay == __delay ;
		};
		// `rhudbg($sformatf("start item:\n%s",_req.sprint()))
		start_item(_req);
		// `rhudbg($sformatf("item(%0d) finished",_req.get_inst_id()))
		finish_item(_req);
	end
endtask


`endif
