`ifndef omosIncr16Test__svh
`define omosIncr16Test__svh

// uvm_test: OmosIncr16Test
// This class generated by snippet: 'test', if has any issue, pls report to RyanHunter
class OmosIncr16Test extends omosBaseTest;
	`uvm_component_utils_begin(OmosIncr16Test)
	`uvm_component_utils_end
	function new(string name="OmosIncr16Test",uvm_component parent=null);
		super.new(name,parent);
	endfunction
	extern virtual task test_sim ();
endclass
task OmosIncr16Test::test_sim();
	RhAhb5Incr16BurstSeq seq=new("incr4");
	seq.randomize();
	seq.start(env.mst.seqr);
endtask

`endif
