`ifndef omosIncrTest__svh
`define omosIncrTest__svh

// uvm_test: OmosIncrTest
// This class generated by snippet: 'test', if has any issue, pls report to RyanHunter
class OmosIncrTest extends omosBaseTest;
	`uvm_component_utils_begin(OmosIncrTest)
	`uvm_component_utils_end
	function new(string name="OmosIncrTest",uvm_component parent=null);
		super.new(name,parent);
	endfunction
	extern virtual task test_sim ();
endclass
task OmosIncrTest::test_sim();
	int i = 0;
	while (i<4) begin
		RhAhb5IncrBurstSeq seq=new("incr");
		seq.len = i+1;
		seq.randomize() with {
			__delay inside {[0:100]};
		};
		`uvm_info("DEBUG",$sformatf("sending incr seq:\n%s",seq.sprint()),UVM_LOW)
		seq.start(env.mst.seqr);
		i++;
	end
endtask

`endif
