`ifndef omosIncr8Test__svh
`define omosIncr8Test__svh

// uvm_test: OmosIncr8Test
// This class generated by snippet: 'test', if has any issue, pls report to RyanHunter
class OmosIncr8Test extends omosBaseTest;
	`uvm_component_utils_begin(OmosIncr8Test)
	`uvm_component_utils_end
	function new(string name="OmosIncr8Test",uvm_component parent=null);
		super.new(name,parent);
	endfunction
	extern virtual task test_sim ();
endclass
task OmosIncr8Test::test_sim();
	RhAhb5Incr8BurstSeq seq=new("incr4");
	seq.randomize();
	seq.start(env.mst.seqr);
endtask

`endif
