`ifndef omosSingleTest__svh
`define omosSingleTest__svh

// uvm_test: OmosSingleTest
// This class generated by snippet: 'test', if has any issue, pls report to RyanHunter
class OmosSingleTest extends omosBaseTest;
	`uvm_component_utils_begin(OmosSingleTest)
	`uvm_component_utils_end
	function new(string name="OmosSingleTest",uvm_component parent=null);
		super.new(name,parent);
	endfunction
	extern virtual task test_sim ();
endclass
task OmosSingleTest::test_sim();
	RhAhb5SingleBurstSeq seq=new("single");
	seq.randomize();
	seq.start(env.mst.seqr);
endtask

`endif
