`ifndef omosIncr4Test__svh
`define omosIncr4Test__svh

// uvm_test: OmosIncr4Test
// This class generated by snippet: 'test', if has any issue, pls report to RyanHunter
class OmosIncr4Test extends omosBaseTest;
	`uvm_component_utils_begin(OmosIncr4Test)
	`uvm_component_utils_end
	function new(string name="OmosIncr4Test",uvm_component parent=null);
		super.new(name,parent);
	endfunction
	extern virtual task test_sim ();
endclass
task OmosIncr4Test::test_sim();
	RhAhb5Incr4BurstSeq seq=new("incr4");
	seq.randomize();
	seq.start(env.mst.seqr);
endtask

`endif
