`ifndef RhResetTransBase__svh
`define RhResetTransBase__svh
/************************************************************************************/
// Author: RyanHunter
// Created: 2022-12-21 03:32:45 -0800
// Description:
// This file is automatically generated by MDC-v2, any issues found
// here should be modified in its source markdown document the same
// dir structure in Git/Obsidian/...
/************************************************************************************/

class RhResetTransBase extends uvm_sequence_item;
	RhResetStateEnum state;
	`uvm_object_utils_begin(RhResetTransBase)
	`uvm_object_utils_end
	extern function  new(string name="RhResetTransBase");
endclass
function  RhResetTransBase::new(string name="RhResetTransBase");
	super.new(name);
endfunction

`endif
