`ifndef RhVipTypes__svh
`define RhVipTypes__svh
/************************************************************************************/
// Author: RyanHunter
// Created: 2022-12-21 03:32:45 -0800
// Description:
// This file is automatically generated by MDC-v2, any issues found
// here should be modified in its source markdown document the same
// dir structure in Git/Obsidian/...
/************************************************************************************/

typedef enum logic {
	RhResetUnknow   = 'bx,
	RhResetFloating = 'bz,
	RhResetActive   = 'b0,
	RhResetInactive = 'b1
} RhResetStateEnum;
`uvm_analysis_imp_decl(_reset)

`endif
